include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

stages:
  - test
  - publish

test-php:
  stage: test
  image:
    name: docker-registry.wikimedia.org/releng/composer-test-php74:0.1.2
    entrypoint: [ "" ]
  allow_failure: false
  script:
    - composer install --prefer-dist --no-progress --no-suggest
    - composer run-script test

test-nodejs:
  stage: test
  image:
    name: docker-registry.wikimedia.org/releng/node16-test:0.2.1
    entrypoint: [ "" ]
  allow_failure: false
  script:
    - npm ci
    - npm run build --if-present
    - npm test

publish:
  stage: publish
  variables:
    BUILD_VARIANT: patchdemo
    PUBLISH_IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
    PUBLISH_IMAGE_EXTRA_TAGS: latest

  extends: .kokkuri:build-and-publish-image
  tags:
    - trusted
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED

