apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-cron-job
spec:
  schedule: "0 0 * * *" 
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: git-fetch-gc
            image: alpine/git
            volumeMounts:
            - name: wiki-repos
              mountPath: /srv/repo-pool/wiki-repos
            command: ["/bin/sh", "-c"]
            args:
              - |
                error_flag=0
                for dir in core parsoid; do
                  cd /srv/repo-pool/wiki-repos/$dir && git fetch --all && git gc || error_flag=1
                done
                for dir in extensions skins build; do
                  for sub_dir in /srv/repo-pool/wiki-repos/$dir/*; do
                    if [ -d "$sub_dir/.git" ]; then
                      cd "$sub_dir" && git fetch --all && git gc || error_flag=1
                    fi
                  done
                done

                if [ "$error_flag" -ne 0 ]; then
                  exit 1
                fi
          restartPolicy: OnFailure
          volumes:
          - name: wiki-repos
            persistentVolumeClaim:
              claimName: patchdemo-wiki-repos-pvc
