apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "patchdemo.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 80Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patchdemo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "patchdemo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "patchdemo.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_USER
              value: "{{ .Values.mariadb.auth.username }}"
            - name: DB_PASS
              value: "{{ .Values.mariadb.auth.password }}"
            - name: DB_HOST
              value: "{{ .Release.Name }}-{{ .Values.app.db.host }}"
            - name: DB_DATABASE
              value: "{{ .Values.mariadb.auth.database }}"
            - name: NEW_WIKI_WARNING
              value: "{{ .Values.app.newWikiWarning }}"
            - name: PHABRICATOR_URL
              value: "{{ .Values.app.phabricatorUrl }}"
            - name: GERRIT_URL
              value: "{{ .Values.app.gerritUrl }}"
            - name: CATALYST_API_URL
              value: "{{ .Values.app.catalystApiUrl }}"
            - name: CATALYST_DOMAIN_NAME
              value: "{{ .Values.app.catalystDomainName }}"
            - name: CATALYST_API_TOKEN
              value: "{{ .Values.app.catalystApiToken }}"
            - name: STATUS_URL
              value: "{{ .Values.app.statusUrl }}"
            - name: REQUIRE_VERIFIED
              value: "{{ .Values.app.requireVerified }}"
            - name: OAUTH_URL
              value: "{{ .Values.app.oauthUrl }}"
            - name: OAUTH_CALLBACK
              value: "{{ .Values.app.oauthCallback }}"
            - name: OAUTH_CONSUMER_KEY
              value: "{{ .Values.app.oauthConsumerKey }}"
            - name: OAUTH_CONSUMER_SECRET
              value: "{{ .Values.app.oauthConsumerSecret }}"
            - name: ADMIN_USERS
              value: "{{ .Values.app.adminUsers }}"
            - name: CONDUIT_API_KEY
              value: "{{ .Values.app.conduitApiKey }}"
          volumeMounts:
            - name: wikis
              mountPath: var/www/html/wikis
            - name: log-volume
              mountPath: /var/log/apache2
        - name: tail-access-log
          image: busybox
          command: ["sh", "-c", "tail -f /var/log/apache2/access.log"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/apache2
        - name: tail-error-log
          image: busybox
          command: ["sh", "-c", "tail -f /var/log/apache2/error.log"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/apache2
        - name: tail-other-vhosts-access-log
          image: busybox
          command: ["sh", "-c", "tail -f /var/log/apache2/other_vhosts_access.log"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/apache2
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /var/log/apache2"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/apache2
      volumes:
        - name: wikis
          persistentVolumeClaim:
            claimName: {{ include "patchdemo.fullname" . }}
        - name: log-volume
