apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "patchdemo.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 80Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patchdemo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "patchdemo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "patchdemo.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_USER
              value: "{{ .Values.mariadb.auth.username }}"
            - name: DB_PASS
              value: "{{ .Values.mariadb.auth.password }}"
            - name: DB_HOST
              value: "{{ .Release.Name }}-{{ .Values.app.db.host }}"
            - name: DB_DATABASE
              value: "{{ .Values.mariadb.auth.database }}"
            - name: CATALYST_API_URL
              value: "{{ .Values.app.catalystApiUrl }}"
            - name: CATALYST_API_TOKEN
              value: "{{ .Values.app.catalystApiToken }}"
          volumeMounts:
            - name: wikis
              mountPath: var/www/html/wikis
      volumes:
        - name: wikis
          persistentVolumeClaim:
            claimName: {{ include "patchdemo.fullname" . }}



