{{ if .Values.wikiReposPool.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "patchdemo.fullname" . }}-repo-pool-pv
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.wikiReposPool.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "patchdemo.fullname" . }}-repo-pool-pvc
spec:
  volumeName: {{ include "patchdemo.fullname" . }}-repo-pool-pv
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "patchdemo.fullname" . }}-repos-config
data:
  repos.cfg: |
{{ $.Files.Get "files/repos.cfg" | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "patchdemo.fullname" . }}-sessions
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "patchdemo.fullname" . }}-repositories
  annotations:
    helm.sh/resource-policy: keep
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "patchdemo.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 80Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patchdemo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "patchdemo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "patchdemo.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "/var/www/html/entrypoint.sh"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_USER
              value: "{{ .Values.mariadb.auth.username }}"
            - name: DB_PASS
              value: "{{ .Values.mariadb.auth.password }}"
            - name: DB_HOST
              value: "{{ .Release.Name }}-{{ .Values.app.db.host }}"
            - name: DB_DATABASE
              value: "{{ .Values.mariadb.auth.database }}"
            - name: NEW_WIKI_WARNING
              value: "{{ .Values.app.newWikiWarning }}"
            - name: NOTIFICATION_BANNER
              value: "{{ .Values.app.notificationBanner }}"
            - name: PHABRICATOR_URL
              value: "{{ .Values.app.phabricatorUrl }}"
            - name: GERRIT_URL
              value: "{{ .Values.app.gerritUrl }}"
            - name: CATALYST_API_URL
              value: "{{ .Values.app.catalystApiUrl }}"
            - name: CATALYST_DOMAIN_NAME
              value: "{{ .Values.app.catalystDomainName }}"
            - name: CATALYST_API_TOKEN
              value: "{{ .Values.app.catalystApiToken }}"
            - name: STATUS_URL
              value: "{{ .Values.app.statusUrl }}"
            - name: REQUIRE_VERIFIED
              value: "{{ .Values.app.requireVerified }}"
            - name: OAUTH_URL
              value: "{{ .Values.app.oauthUrl }}"
            - name: OAUTH_CALLBACK
              value: "{{ .Values.app.oauthCallback }}"
            - name: OAUTH_CONSUMER_KEY
              value: "{{ .Values.app.oauthConsumerKey }}"
            - name: OAUTH_CONSUMER_SECRET
              value: "{{ .Values.app.oauthConsumerSecret }}"
            - name: ADMIN_USERS
              value: "{{ .Values.app.adminUsers }}"
            - name: CONDUIT_API_KEY
              value: "{{ .Values.app.conduitApiKey }}"
            - name: REPO_POOL_HOST_PATH
              value: "{{ .Values.wikiReposPool.hostPath }}"
          volumeMounts:
            - name: wikis
              mountPath: /var/www/html/wikis
            - name: sessions
              mountPath: /var/lib/php/sessions
            - name: log-volume
              mountPath: /var/log/apache2
            - name: repositories
              mountPath: /var/www/html/repositories
{{- if .Values.wikiReposPool.enabled }}
            - name: repos-config
              mountPath: /var/www/html/repository-lists/config
            - name: repo-pool
              mountPath: /srv/repo-pool/wiki-repos
              readOnly: true
{{- end }}
        - name: tail-access-log
          image: busybox
          command: ["sh", "-c", "tail -f /var/log/apache2/access.log"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/apache2
        - name: tail-error-log
          image: busybox
          command: ["sh", "-c", "tail -f /var/log/apache2/error.log"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/apache2
        - name: tail-other-vhosts-access-log
          image: busybox
          command: ["sh", "-c", "tail -f /var/log/apache2/other_vhosts_access.log"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/apache2
      initContainers:
{{- if .Values.wikiReposPool.enabled }}
        - name: clone-wikis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu pipefail
              
              cd /var/www/html/repositories
              while IFS=' ' read -r repo dir; do
                while [ ! -d "$REPO_POOL_MOUNT_PATH/$repo/.git" ]; do
                  echo "Waiting for $repo to be available in repo pool"
                  sleep 30
                done
                if [ ! -d "$repo" ]; then
                  git clone --no-checkout https://gerrit.wikimedia.org/r/$repo.git $repo --reference $REPO_POOL_MOUNT_PATH/$repo
                fi
              done < ../repository-lists/config/repos.cfg
              cd ..
          env:
            - name: REPO_POOL_MOUNT_PATH
              value: /srv/repo-pool/wiki-repos
          volumeMounts:
            - name: repo-pool
              mountPath: /srv/repo-pool/wiki-repos
              readOnly: true
            - name: repos-config
              mountPath: /var/www/html/repository-lists/config
            - name: repositories
              mountPath: /var/www/html/repositories
{{- else }}
        - name: clone-wikis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              set -eu pipefail
              
              cd /var/www/html/repositories
              while IFS=' ' read -r repo dir; do
                git clone --no-checkout https://gerrit.wikimedia.org/r/$repo.git $repo
              done < ../repository-lists/all.txt
              cd ..
          volumeMounts:
            - name: repositories
              mountPath: /var/www/html/repositories
{{- end }}
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /var/log/apache2"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/apache2
      volumes:
        - name: wikis
          persistentVolumeClaim:
            claimName: {{ include "patchdemo.fullname" . }}
        - name: sessions
          persistentVolumeClaim:
            claimName: {{ include "patchdemo.fullname" . }}-sessions
        - name: repositories
          persistentVolumeClaim:
            claimName: {{ include "patchdemo.fullname" . }}-repositories
{{- if .Values.wikiReposPool.enabled }}
        - name: repo-pool
          persistentVolumeClaim:
            claimName: {{ include "patchdemo.fullname" . }}-repo-pool-pvc
        - name: repos-config
          configMap:
            name: {{ include "patchdemo.fullname" . }}-repos-config
{{- end }}
        - name: log-volume
